### ISSUE TITLE
Class Sqed::BoundaryFinder::ColorLineFinder might cause a fault.

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/sqed#1]
During pre-processing, if an image is supplied which does *not* fit the supplied configuration, 

As an example (when used in conjunction with TaxonWorks)
`rake tw:batch_load:sqed_depiction:import total=1 layout=seven_slot metadata_map='{"0": "collecting_event_labels", "1": "determination_labels", "2": "other_labels", "3": "image_registration", "4": "curator_metadata", "5": "identifier", "6": "specimen"}' boundary_finder='Sqed::BoundaryFinder::ColorLineFinder' boundary_color=red preprocess_result=true project_id=1 user_id=1 data_directory=~/Desktop/stage_images/`,
and the data_directory contains `CrossyBlackLinesSpecimen.jpg`,
rhe rake task is aborted with the following stack:
`rake aborted!
NoMethodError: undefined method '[]' for nil:NilClass
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/sqed-0.4.1/lib/sqed/boundary_finder.rb:231:in 'corrected_frequency'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/sqed-0.4.1/lib/sqed/boundary_finder/color_line_finder.rb:44:in 'find_bands'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/sqed-0.4.1/lib/sqed/boundary_finder/color_line_finder.rb:25:in 'initialize'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/sqed-0.4.1/lib/sqed.rb:214:in 'new'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/sqed-0.4.1/lib/sqed.rb:214:in 'get_section_boundaries'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/sqed-0.4.1/lib/sqed.rb:103:in 'boundaries'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/sqed-0.4.1/lib/sqed.rb:142:in 'result'
/Users/tuckerjd/src/taxonworks/lib/vendor/sqed_to_taxonworks.rb:75:in 'sqed_result'
/Users/tuckerjd/src/taxonworks/lib/vendor/sqed_to_taxonworks.rb:99:in 'cache_ocr'
/Users/tuckerjd/src/taxonworks/lib/vendor/sqed_to_taxonworks.rb:103:in 'cache_all'
/Users/tuckerjd/src/taxonworks/app/models/sqed_depiction.rb:106:in 'preprocess'
/Users/tuckerjd/src/taxonworks/lib/tasks/batch_load/sqed_depictions.rake:96:in 'block (7 levels) in <top (required)>'
/Users/tuckerjd/src/taxonworks/lib/tasks/batch_load/sqed_depictions.rake:67:in 'each'
/Users/tuckerjd/src/taxonworks/lib/tasks/batch_load/sqed_depictions.rake:67:in 'block (6 levels) in <top (required)>'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in 'block in transaction'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194:in 'block in within_new_transaction'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in 'within_new_transaction'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in 'transaction'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in 'transaction'
/Users/tuckerjd/src/taxonworks/lib/tasks/batch_load/sqed_depictions.rake:66:in 'block (5 levels) in <top (required)>'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/core_ext/array/grouping.rb:37:in 'block in in_groups_of'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/core_ext/array/grouping.rb:37:in 'each'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/core_ext/array/grouping.rb:37:in 'each_slice'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.6/lib/active_support/core_ext/array/grouping.rb:37:in 'in_groups_of'
/Users/tuckerjd/src/taxonworks/lib/tasks/batch_load/sqed_depictions.rake:65:in 'block (4 levels) in <top (required)>'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/gems/rake-12.3.1/exe/rake:27:in '<top (required)>'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:15:in 'eval'
/Users/tuckerjd/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:15:in '<main>'
Tasks: TOP => tw:batch_load:sqed_depiction:import`

I have traced this to the fact that in line 44 of `color_line_finder.rb`, the method call of `Sqed::BoundaryFinder.color_boundary_finder(image: right_top_image, boundary_color: boundary_color)` results in a nil return, which is passed to `corrected_frequency` (`boundary_line_finder.rb`, line 231) as the `frequency_stats` parameter, which is immediately treated as an Array, causing the fault.

**Comment by mjy** [comment]
Closing as outdated.
